language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest
    - pip install pytest-cov
    - pip install flake8
    - pip install -e .
    - pip install coveralls
script:
    - py.test --cov-report term-missing --cov=comengine tests
    - flake8 comengine tests example.py setup.py --max-line-length=120 --ignore=F401,W504
after_success:
    - coveralls
